"""Secure file storage and validation.

* Validates extension AND content signature (magic bytes), not the browser's MIME claim.
* Stores files under STORAGE_DIR (outside any served/static directory) with random names.
* Files are only ever read as data; nothing is executed.
"""
import hashlib
import io
import os
import secrets
import zipfile

from flask import current_app

from ..errors import ApiError

RESUME_TYPES = {
    "pdf": "application/pdf",
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "txt": "text/plain",
}
IMAGE_TYPES = {"png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg", "webp": "image/webp"}


class FileRejected(ApiError):
    status, code = 400, "invalid_file"


def _extension(filename):
    if not filename or "." not in filename:
        return ""
    return filename.rsplit(".", 1)[1].lower()


def _sniff_resume(ext, head: bytes, data: bytes):
    if ext == "pdf":
        return head.startswith(b"%PDF-")
    if ext == "docx":
        if not head.startswith(b"PK\x03\x04"):
            return False
        try:
            with zipfile.ZipFile(io.BytesIO(data)) as zf:
                names = set(zf.namelist())
                if "word/document.xml" not in names:
                    return False
                # Reject macro-enabled documents disguised as .docx
                if any(n.lower().endswith("vbaproject.bin") for n in names):
                    return False
                # Zip-bomb guard
                if sum(i.file_size for i in zf.infolist()) > 100 * 1024 * 1024:
                    return False
            return True
        except zipfile.BadZipFile:
            return False
    if ext == "txt":
        if b"\x00" in data[:8192]:
            return False
        try:
            data[:65536].decode("utf-8")
            return True
        except UnicodeDecodeError:
            try:
                data[:65536].decode("latin-1")
                return True
            except UnicodeDecodeError:
                return False
    return False


def _sniff_image(ext, head):
    if ext == "png":
        return head.startswith(b"\x89PNG\r\n\x1a\n")
    if ext in ("jpg", "jpeg"):
        return head.startswith(b"\xff\xd8\xff")
    if ext == "webp":
        return head[:4] == b"RIFF" and head[8:12] == b"WEBP"
    return False


def read_upload(file_storage, kind="resume"):
    """Validate an uploaded werkzeug FileStorage. Returns (data, ext, mime)."""
    if file_storage is None or not file_storage.filename:
        raise FileRejected("No file was uploaded.")
    ext = _extension(file_storage.filename)
    allowed = RESUME_TYPES if kind == "resume" else IMAGE_TYPES
    if ext not in allowed:
        nice = ", ".join(sorted(e.upper() for e in allowed))
        raise FileRejected(f"Unsupported file type. Allowed: {nice}.", code="unsupported_file_type")
    limit = current_app.config["MAX_RESUME_BYTES" if kind == "resume" else "MAX_AVATAR_BYTES"]
    data = file_storage.read(limit + 1)
    if len(data) > limit:
        raise FileRejected(f"File is too large. The maximum size is {limit // (1024 * 1024)} MB.",
                           code="file_too_large")
    if not data:
        raise FileRejected("The uploaded file is empty.")
    head = data[:16]
    ok = _sniff_resume(ext, head, data) if kind == "resume" else _sniff_image(ext, head)
    if not ok:
        raise FileRejected("The file content does not match its extension or the file is corrupted.",
                           code="content_mismatch")
    return data, ext, allowed[ext]


def _root():
    root = current_app.config["STORAGE_DIR"]
    os.makedirs(root, mode=0o700, exist_ok=True)
    return root


def save_bytes(data: bytes, ext: str):
    name = f"{secrets.token_hex(16)}.{ext}"
    path = os.path.join(_root(), name)
    # O_EXCL: never overwrite; 0o600: owner read/write only, never executable.
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "wb") as fh:
        fh.write(data)
    return name, hashlib.sha256(data).hexdigest()


def path_for(stored_name: str) -> str:
    # stored names are generated by us; still guard against traversal.
    if not stored_name or os.path.basename(stored_name) != stored_name or stored_name.startswith("."):
        raise FileRejected("Invalid file reference.")
    return os.path.join(_root(), stored_name)


def delete_file(stored_name):
    if not stored_name:
        return
    try:
        os.remove(path_for(stored_name))
    except FileNotFoundError:
        pass


def cleanup_orphans(known_names):
    """Delete stored files no longer referenced by the database. Returns count removed."""
    removed = 0
    root = _root()
    for name in os.listdir(root):
        if name not in known_names and not name.startswith("."):
            try:
                os.remove(os.path.join(root, name))
                removed += 1
            except OSError:
                pass
    return removed
